spring:
  h2:
    console:
      enabled: true
  data:
    jdbc:
      repositories:
        enabled: true
logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: debug