constructor:
  record-year: 2020
  api:
    name: kakao
    key: 123123

external:
  record-year: 2020
  api:
    name: kakao
    key: 123123

type-safe:
  record-year: 2020
  api:
    name: kakao
    key: 123123

problem:
  value: true